Repository Maathru/Backend, pull requests merged in 2024-12, with the labels that each got.

#72 dev 5 commits behind main
  src/main/java/com/maathru/backend/Application/controllers/v1/GrowthController.java
  src/main/java/com/maathru/backend/Application/dto/response/PregnancyCardForGrowthResponse.java
  src/main/java/com/maathru/backend/Domain/entity/PregnancyCard.java
  src/main/java/com/maathru/backend/Domain/service/GrowthService.java
  src/main/java/com/maathru/backend/External/repository/ParentRepository.java
  src/main/java/com/maathru/backend/External/repository/PregnancyCardRepository.java
Labels: enhancement

#73 Chat done
  pom.xml
  src/main/java/com/maathru/backend/Application/config/CorsConfig.java
  src/main/java/com/maathru/backend/Application/config/SecurityConfig.java
  src/main/java/com/maathru/backend/Application/config/WebSocketConfig.java
  src/main/java/com/maathru/backend/Application/controllers/v1/ChatController.java
  src/main/java/com/maathru/backend/Application/dto/response/ChatNotification.java
  src/main/java/com/maathru/backend/Application/dto/response/ChatUserDto.java
  src/main/java/com/maathru/backend/BackendApplication.java
  src/main/java/com/maathru/backend/Domain/entity/chat/ChatMessage.java
  src/main/java/com/maathru/backend/Domain/entity/chat/ChatRoom.java
  src/main/java/com/maathru/backend/Domain/entity/chat/ChatUser.java
  src/main/java/com/maathru/backend/Domain/service/chat/ChatMessageService.java
  src/main/java/com/maathru/backend/Domain/service/chat/ChatRoomService.java
  src/main/java/com/maathru/backend/Domain/service/chat/ChatUserService.java
  src/main/java/com/maathru/backend/External/repository/chat/ChatMessageRepository.java
  src/main/java/com/maathru/backend/External/repository/chat/ChatRoomRepository.java
  src/main/java/com/maathru/backend/External/repository/chat/ChatUserRepository.java
  src/main/java/com/maathru/backend/enumeration/Status.java
Labels: enhancement

#74 Pregnancy card for midwife
  src/main/java/com/maathru/backend/Application/controllers/v1/EligibleController.java
  src/main/java/com/maathru/backend/Application/controllers/v1/ParentController.java
  src/main/java/com/maathru/backend/Domain/service/EligibleService.java
  src/main/java/com/maathru/backend/Domain/service/ParentService.java
Labels: documentation, enhancement

#75 Analytics
  src/main/java/com/maathru/backend/Application/controllers/v1/AnalyticsController.java
  src/main/java/com/maathru/backend/Domain/entity/PregnancyCard.java
  src/main/java/com/maathru/backend/Domain/service/AnalyticsService.java
  src/main/java/com/maathru/backend/External/repository/ChildBirthRepository.java
  src/main/java/com/maathru/backend/External/repository/OtherSituationRepository.java
  src/main/java/com/maathru/backend/External/repository/PregnancyCardRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/BasicInfoRepository.java
Labels: enhancement

#77 medical record addded
  src/main/java/com/maathru/backend/Application/controllers/v1/MedicalRecordController.java
  src/main/java/com/maathru/backend/Application/dto/response/MedicalRecordResponse.java
  src/main/java/com/maathru/backend/Domain/entity/MedicalRecord.java
  src/main/java/com/maathru/backend/Domain/service/MedicalRecordService.java
  src/main/java/com/maathru/backend/External/repository/MedicalRecordRepository.java
Labels: enhancement

#78 Edit profile done
  src/main/java/com/maathru/backend/Application/config/InitialDataLoader.java
  src/main/java/com/maathru/backend/Application/controllers/v1/UserController.java
  src/main/java/com/maathru/backend/Application/dto/request/UpdateEmployeeProfileDto.java
  src/main/java/com/maathru/backend/Application/dto/request/UpdateUserProfileDto.java
  src/main/java/com/maathru/backend/Application/dto/response/UserProfileDto.java
  src/main/java/com/maathru/backend/Domain/service/UserService.java
  src/main/java/com/maathru/backend/External/repository/EmployeeRepository.java
Labels: documentation

#81 Medical records
  src/main/java/com/maathru/backend/Application/config/DataSeeder.java
  src/main/java/com/maathru/backend/External/repository/EmployeeRepository.java
Labels: bug

#85 Home visit add
  src/main/java/com/maathru/backend/Application/controllers/v1/ClinicController.java
  src/main/java/com/maathru/backend/Application/dto/request/HomeVisitRequest.java
  src/main/java/com/maathru/backend/Application/dto/request/VisitDto.java
  src/main/java/com/maathru/backend/Domain/entity/HomeVisit.java
  src/main/java/com/maathru/backend/Domain/entity/Visit.java
  src/main/java/com/maathru/backend/Domain/service/ClinicService.java
  src/main/java/com/maathru/backend/External/repository/HomeVisitRepository.java
  src/main/java/com/maathru/backend/External/repository/VisitRepository.java
  src/main/java/com/maathru/backend/enumeration/VisitStatus.java
Labels: documentation, enhancement

#87 Midwife home visits done
  src/main/java/com/maathru/backend/Application/controllers/v1/ClinicController.java
  src/main/java/com/maathru/backend/Application/controllers/v1/VisitsController.java
  src/main/java/com/maathru/backend/Application/dto/response/HomeVisitsListResponse.java
  src/main/java/com/maathru/backend/Domain/entity/VisitSchedule.java
  src/main/java/com/maathru/backend/Domain/service/ClinicService.java
  src/main/java/com/maathru/backend/Domain/service/RegionService.java
  src/main/java/com/maathru/backend/Domain/service/VisitsService.java
  src/main/java/com/maathru/backend/External/repository/HomeVisitRepository.java
  src/main/java/com/maathru/backend/External/repository/VisitScheduleRepository.java
  src/main/resources/application.properties
Labels: documentation

#88 Parent clnics fetch
  src/main/java/com/maathru/backend/Application/controllers/v1/VisitsController.java
  src/main/java/com/maathru/backend/Domain/service/VisitsService.java
  src/main/java/com/maathru/backend/External/repository/HomeVisitRepository.java
Labels: documentation

#89 Home visit for midwife
  src/main/java/com/maathru/backend/Application/dto/response/HomeVisitsListResponse.java
  src/main/java/com/maathru/backend/Application/dto/response/HomeVisitsResponse.java
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
  src/main/java/com/maathru/backend/External/repository/HomeVisitRepository.java
Labels: documentation

#90 fixed designation issue
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
Labels: bug
