Repository Maathru/Backend, pull requests merged in 2024-11, with the labels that each got.

#48 Employee sign up done
  src/main/java/com/maathru/backend/Application/controllers/v1/AuthenticationController.java
  src/main/java/com/maathru/backend/Application/controllers/v1/EmployeeController.java
  src/main/java/com/maathru/backend/Application/dto/request/EmployeeDto.java
  src/main/java/com/maathru/backend/Domain/entity/Employee.java
  src/main/java/com/maathru/backend/Domain/service/AuthenticationService.java
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
  src/main/java/com/maathru/backend/Domain/service/UserService.java
  src/main/java/com/maathru/backend/Domain/validation/ValidNIC.java
  src/main/java/com/maathru/backend/Domain/validation/impl/NICValidator.java
  src/main/java/com/maathru/backend/External/utils/EmailUtils.java
Labels: documentation

#49 Fixed employee registration
  src/main/java/com/maathru/backend/Application/controllers/v1/AuthenticationController.java
  src/main/java/com/maathru/backend/Application/controllers/v1/EmployeeController.java
  src/main/java/com/maathru/backend/Application/dto/request/EmployeeDto.java
  src/main/java/com/maathru/backend/Domain/service/AuthenticationService.java
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
  src/main/java/com/maathru/backend/Domain/service/UserService.java
  src/main/java/com/maathru/backend/Domain/validation/impl/NICValidator.java
Labels: documentation

#50 Fixed parent status change bug
  src/main/java/com/maathru/backend/Application/dto/eligible/EligibleCoupleDTO.java
  src/main/java/com/maathru/backend/Domain/service/EligibleService.java
  src/main/java/com/maathru/backend/Domain/validation/impl/NICValidator.java
Labels: documentation

#51 Eligible couple deletion
  src/main/java/com/maathru/backend/Application/controllers/v1/EligibleController.java
  src/main/java/com/maathru/backend/Domain/entity/Auditable.java
  src/main/java/com/maathru/backend/Domain/service/EligibleService.java
  src/main/java/com/maathru/backend/External/repository/eligible/BasicInfoRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/FamilyHealthInfoRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/FamilyNutritionRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/HomeEnvironmentRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/MedicalHistoryRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/MidwifeAssessmentRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/ParentHabitRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/SpecialBothRepository.java
  src/main/java/com/maathru/backend/External/repository/eligible/SpecialWomanRepository.java
Labels: documentation

#52 Clinic
  src/main/java/com/maathru/backend/Application/controllers/v1/ClinicController.java
  src/main/java/com/maathru/backend/Application/dto/response/ClinicResponse.java
  src/main/java/com/maathru/backend/Domain/service/ClinicService.java
  src/main/java/com/maathru/backend/External/repository/ClinicRepository.java
Labels: documentation

#53 Fixed no args constructer issue in region response
  src/main/java/com/maathru/backend/Application/dto/response/ClinicResponse.java
  src/main/java/com/maathru/backend/Application/dto/response/RegionResponse.java
Labels: documentation

#54 Pregnancy card data cru
  src/main/java/com/maathru/backend/Application/controllers/v1/ParentController.java
  src/main/java/com/maathru/backend/Application/dto/eligible/BasicInfoDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/ChildBirthDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/ClinicalConservationDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/CurrentPregnancyDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/FamilyHistoryDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/ParentDetailsDto.java
  src/main/java/com/maathru/backend/Application/dto/parent/PregnancyHistoryDto.java
  src/main/java/com/maathru/backend/Domain/entity/eligible/BasicInfo.java
  src/main/java/com/maathru/backend/Domain/entity/eligible/MedicalHistory.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ChildBirth.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ChildDetail.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ChildDetailRepository.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ClinicalConservation.java
  src/main/java/com/maathru/backend/Domain/entity/parent/CurrentPregnancy.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ObstetricComplication.java
  src/main/java/com/maathru/backend/Domain/entity/parent/OtherSituation.java
  src/main/java/com/maathru/backend/Domain/entity/parent/PreExistingMedicalCondition.java
  src/main/java/com/maathru/backend/Domain/entity/parent/PregnancyHistory.java
  src/main/java/com/maathru/backend/Domain/mapper/BasicInfoMapper.java
  src/main/java/com/maathru/backend/Domain/mapper/ChildBirthMapper.java
  src/main/java/com/maathru/backend/Domain/mapper/CurrentPregnancyMapper.java
  src/main/java/com/maathru/backend/Domain/mapper/FamilyHistoryMapper.java
  src/main/java/com/maathru/backend/Domain/mapper/ParentDetailsMapper.java
  src/main/java/com/maathru/backend/Domain/service/ClinicService.java
  src/main/java/com/maathru/backend/Domain/service/EligibleService.java
  src/main/java/com/maathru/backend/Domain/service/ParentService.java
  src/main/java/com/maathru/backend/External/repository/ChildBirthRepository.java
  src/main/java/com/maathru/backend/External/repository/ClinicalConservationRepository.java
  src/main/java/com/maathru/backend/External/repository/CurrentPregnancyRepository.java
  src/main/java/com/maathru/backend/External/repository/ObstetricComplicationRepository.java
  src/main/java/com/maathru/backend/External/repository/OtherSituationRepository.java
  src/main/java/com/maathru/backend/External/repository/parent/PreExistingMedicalConditionRepository.java
  src/main/java/com/maathru/backend/External/repository/parent/PregnancyHistoryRepository.java
Labels: enhancement

#55 Fetch clinics to doctor by date
  src/main/java/com/maathru/backend/Application/controllers/v1/ClinicController.java
  src/main/java/com/maathru/backend/Application/dto/response/ClinicListResponse.java
  src/main/java/com/maathru/backend/Domain/service/ClinicService.java
  src/main/java/com/maathru/backend/External/repository/ClinicRepository.java
Labels: documentation

#57 fetched data for midwife's individual home visit page
  src/main/java/com/maathru/backend/Application/controllers/v1/EmployeeController.java
  src/main/java/com/maathru/backend/Application/dto/response/HomeVisitsResponse.java
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
  src/main/java/com/maathru/backend/Domain/service/ParentService.java
  src/main/java/com/maathru/backend/External/repository/eligible/BasicInfoRepository.java
  src/main/java/com/maathru/backend/External/repository/parent/ChildDetailRepository.java
Labels: enhancement

#58 Add some error handling logics for getMidwifeHomeVisitsData
  src/main/java/com/maathru/backend/Domain/service/EmployeeService.java
Labels: documentation

#63 Wishwa
  Dockerfile
  docker-compose.yml
  src/main/java/com/maathru/backend/Application/controllers/v1/ParentController.java
  src/main/java/com/maathru/backend/Application/dto/request/ChildMemoryDto.java
  src/main/java/com/maathru/backend/Domain/entity/Employee.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ChildMemory.java
  src/main/java/com/maathru/backend/Domain/service/ParentService.java
  src/main/java/com/maathru/backend/External/repository/parent/ChildMemoryRepository.java
Labels: enhancement

#64 Growth tracker
  src/main/java/com/maathru/backend/Application/controllers/v1/GrowthController.java
  src/main/java/com/maathru/backend/Domain/service/GrowthService.java
Labels: enhancement

#66 String to boolean
  src/main/java/com/maathru/backend/Application/dto/parent/ClinicalConservationDto.java
  src/main/java/com/maathru/backend/Domain/entity/parent/ClinicalConservation.java
Labels: bug

#69 Image upload
  pom.xml
  src/main/java/com/maathru/backend/Application/config/SecurityConfig.java
  src/main/java/com/maathru/backend/Application/config/WebConfig.java
  src/main/java/com/maathru/backend/Application/controllers/v1/ImageController.java
  src/main/java/com/maathru/backend/External/utils/UploadImage.java
  src/main/java/com/maathru/backend/constant/Constant.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#70 Growth track
  src/main/java/com/maathru/backend/Application/controllers/v1/GrowthController.java
  src/main/java/com/maathru/backend/Application/dto/response/PregnancyCardForGrowthResponse.java
  src/main/java/com/maathru/backend/Domain/entity/PregnancyCard.java
  src/main/java/com/maathru/backend/Domain/service/GrowthService.java
  src/main/java/com/maathru/backend/External/repository/ParentRepository.java
  src/main/java/com/maathru/backend/External/repository/PregnancyCardRepository.java
Labels: enhancement
